CREATE TABLE `Student` (
    `S#` VARCHAR(50) NULL DEFAULT NULL,
    `Sname` VARCHAR(50) NULL DEFAULT NULL,
    `Sex` VARCHAR(50) NULL DEFAULT NULL,
    `Bdate` DATE NULL,
    `Height` FLOAT NULL DEFAULT NULL,
    `Dorm` VARCHAR(50) NULL DEFAULT NULL
);
CREATE TABLE `Course` (
    `C#` VARCHAR(50) NULL DEFAULT NULL,
    `Cname` VARCHAR(50) NULL DEFAULT NULL,
    `Period` INT NULL,
    `Credit` FLOAT NULL DEFAULT NULL,
    `Teacher` VARCHAR(50) NULL DEFAULT NULL
);
CREATE TABLE `sc` (
    `S#` VARCHAR(50) NOT NULL,
    `C#` VARCHAR(50) NOT NULL,
    `Grade` INT(11) NULL DEFAULT NULL,
    INDEX `FK_sc_student` (`S#`) USING BTREE,
    INDEX `FK_sc_course` (`C#`) USING BTREE,
    CONSTRAINT `FK_sc_course` FOREIGN KEY (`C#`) REFERENCES `homework`.`course` (`C#`) ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT `FK_sc_student` FOREIGN KEY (`S#`) REFERENCES `homework`.`student` (`S#`) ON UPDATE RESTRICT ON DELETE RESTRICT
);